# Generated by Django 4.1.7 on 2023-02-27 20:10

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=255, unique=True, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=255, null=True, verbose_name='Correo electronico')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Nombre de Usuario')),
                ('telefono', models.CharField(max_length=150, verbose_name='telefono ')),
                ('domicilio', models.CharField(max_length=100, verbose_name='domicilio')),
                ('ciudad', models.CharField(default='ciudad..', max_length=100, verbose_name='ciudad')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
